### ISSUE TITLE
关于 qrpc 的建议

### ISSUE THREAD

**Issue by JeffreyBool** [zhiqiangxu/qrpc#11]
- [ ] serverconn.serve() 方法在建立客户端连接的时候是不是应该提供一个回调函数可控业务方控制建立连接的管理工作

- [ ]  serverconn客户端断开与服务端的连接时候是否可以提供一个回调函数供客户端回收资源

**Comment by JeffreyBool** [comment]
![image](https://user-images.githubusercontent.com/24415888/75243321-a33cb680-5804-11ea-8f74-b9d08e101c75.png)
![image](https://user-images.githubusercontent.com/24415888/75243339-ac2d8800-5804-11ea-9745-fffd0968effc.png)
我加了一个简单的回调，代码很糙

**Comment by zhiqiangxu** [comment]
连接刚建立时没有任何有效信息，在回调里打算做什么呢？

**Comment by JeffreyBool** [comment]
比如加心跳，比如加在线用户管理，加房间等。

**Comment by zhiqiangxu** [comment]
这些都可以在login cmd里面做

**Comment by JeffreyBool** [comment]
然后每个链接是不是应该分配一个唯一链接 ID 呢？ 用来管理， 还是我没看明白，Connection 的时候，这个应该在客户端直接建立和服务端的链接吧？ 这个Connection 是在什么时候用呢？

**Comment by JeffreyBool** [comment]
> 这些都可以在login cmd里面做

这样是不是不太好，依赖 cmd 匹配，依赖必须客户端发消息了才能建立关系。不然不会走 serverQRPC() 函数吧

**Comment by zhiqiangxu** [comment]
不然拿到的是一个裸的socket，也做不了有意义的事

**Comment by JeffreyBool** [comment]
也对。。 但是是不是可以主动给客户端推消息这种场景呢

**Comment by zhiqiangxu** [comment]
没有这种需求

**Comment by JeffreyBool** [comment]
> 没有这种需求

但是心跳是不是不应该依赖 cmd 的匹配呢？依赖必须客户端发消息了才能建立关系。不然不会走 serverQRPC() 函数

**Comment by zhiqiangxu** [comment]
只有你知道了这个连接的某些信息，才有必要做任何处理，拿不到信息的要么是某些端口检查程序或者恶意黑客。

**Comment by zhiqiangxu** [comment]
@JeffreyBool 加了个`ServerLifecycleCallbacks`，目前只会在连接刚建立和断开的时候回调。

https://github.com/zhiqiangxu/qrpc/commit/ead8516f1122a0ac6f73800f55ca3a8e93384206

**Comment by JeffreyBool** [comment]
> @JeffreyBool 加了个`ServerLifecycleCallbacks`，目前只会在连接刚建立和断开的时候回调。
> 
> [ead8516](https://github.com/zhiqiangxu/qrpc/commit/ead8516f1122a0ac6f73800f55ca3a8e93384206)

好的
