### ISSUE TITLE
请教一个关于心跳的问题

### ISSUE THREAD

**Issue by JeffreyBool** [zhiqiangxu/qrpc#12]
请问趣头条内部业务自己实现的心跳是基于时间轮的方式优化心跳吗？

按照传统模式就是一个连接对应一个 协程去检测心跳。这样在少的连接场景是没啥问题的，单在几十万的客户端建立连接的时候，就是 几十万 * 2 的协程数量了。占用的资源还有有必要去优化的

**Comment by zhiqiangxu** [comment]
不用，只要设置DefaultReadTimeout就行了

**Comment by JeffreyBool** [comment]
用 tcp 自己的 time out 机制？但是看网上好像不可靠，比如长连服务给客户端发心跳，或者客户端给长连服务发心跳，其中一方阻塞了就会遇到问题，我看的文章：[http://www.52im.net/thread-281-1-1.html](http://www.52im.net/thread-281-1-1.html)

**Comment by zhiqiangxu** [comment]
不是tcp的，qrpc内部的读超时判断。

**Comment by JeffreyBool** [comment]
![image](https://user-images.githubusercontent.com/24415888/75519582-8986b380-5a3e-11ea-95bb-74a2718d3f5a.png)
我看代码追踪到是这里，这里不是 tcp 自带的 SetReadDeadline 吗

**Comment by zhiqiangxu** [comment]
tcp自带的是KeepAlive

**Comment by JeffreyBool** [comment]
所以设置这个了就不需要在做心跳了是吗？

**Comment by zhiqiangxu** [comment]
嗯，tcp的KeepAlive内部已经做了，如果自己再做心跳的话，就跟这个参数搭配使用就行。

**Comment by JeffreyBool** [comment]
好的，谢了。
