### ISSUE TITLE
请教一个长连系统的问题

### ISSUE THREAD

**Issue by JeffreyBool** [zhiqiangxu/qrpc#13]
你们内部怎么是怎么保证消息的可靠性发送？

例如消息 ack 机制，消息重发是用什么发送呢？
消息队列吗

**Comment by zhiqiangxu** [comment]
跟这个是同一个问题  https://github.com/zhiqiangxu/qrpc/issues/3

**Comment by JeffreyBool** [comment]
> 跟这个是同一个问题 #3

能说一下具体实现在哪个文件吗

**Comment by zhiqiangxu** [comment]
这个需要上层控制，rpc是不保障的。可以去一些专门的im项目讨论。

**Comment by JeffreyBool** [comment]
> 这个需要上层控制，rpc是不保障的。可以去一些专门的im项目讨论。

好的
