### ISSUE TITLE
关于ConnectionInfo  实例 向客户端 写入的问题

### ISSUE THREAD

**Issue by JeffreyBool** [zhiqiangxu/qrpc#14]
基于 qrpc 开发个群聊系统，系统保存用户实例，用户实例保存了 qrpc.ConnectionInfo 的指针， 这时需要向客户端主动推送消息。

这时候是直接调用qrpc.ConnectionInfo 的 GetWriter() 方法向客户端写入消息吗？

![image](https://user-images.githubusercontent.com/24415888/76057098-5484de80-5fb3-11ea-82e3-cf950a0de65a.png)
例如上面这样，我用这种方式第一条消息可以正常到达客户端，第二条以下的消息就会出现 `write after closeself` 错误，请问是什么原因引起的呢

**Comment by zhiqiangxu** [comment]
因为qrpc内部有流的概念，如果是主动推送，需要加上`qrpc.PushFlag`

**Comment by JeffreyBool** [comment]
所以客户端没有跟服务器发送消息，例如没有走 cmd 的 消息， 服务端主动向客户端发送消息，服务端就需要加上`qrpc.PushFlag`, 如果是客户端给客户端发了消息，并且这个消息走的 cmd 机制，这时候服务端回复客户端就需要加上 `qrpc.NBFlag` 对吗

**Comment by zhiqiangxu** [comment]
> 所以客户端没有跟服务器发送消息，例如没有走 cmd 的 消息， 服务端主动向客户端发送消息，服务端就需要加上`qrpc.PushFlag`, 如果是客户端给客户端发了消息，并且这个消息走的 cmd 机制，这时候服务端回复客户端就需要加上 `qrpc.NBFlag` 对吗

`qrpc.PushFlag` 用于主动推送的情况。
回复的时候也不需要加`qrpc.NBFlag`。
