### ISSUE TITLE
有没有想过使用epoll 优化连接 goroutine 数量

### ISSUE THREAD

**Issue by YIDWang** [zhiqiangxu/qrpc#2]

**Comment by zhiqiangxu** [comment]
这个在ppt中应该提到了，规划中，不过目前一个tcp连接2个协程，其实内存占用已经很小（比grpc少1个协程）。集成epoll后连接数跟协程数就没线性关系了。

**Comment by YIDWang** [comment]
https://colobu.com/2019/02/23/1m-go-tcp-connection/ 可以参考这篇文章，内存优化还是比较显著的

美图刚刚开源一个长链接项目 ，网络调度就是依靠 epoll 实现。https://github.com/meitu/bifrost。

**Comment by zhiqiangxu** [comment]
当同时在线到了千万级别，做这个优化就很有必要了，目前我们还是几百万级别，所以规划中但低优。

**Comment by YIDWang** [comment]
好的 感谢回复
