### ISSUE TITLE
qrpc 如何管理消息下发的可靠性

### ISSUE THREAD

**Issue by YIDWang** [zhiqiangxu/qrpc#3]
* At least one
* At most once

这两个级别如何保证

**Comment by zhiqiangxu** [comment]
这两个其实不是协议层面保障的，就像grpc也不会保障这方面。这个需要上层业务去实现，有兴趣可以关注下这个项目：https://github.com/zhiqiangxu/qq，不过还在早期阶段，底层模块：https://github.com/zhiqiangxu/util/tree/master/diskqueue 还在优化中。

**Comment by YIDWang** [comment]
好的 明白了
