### ISSUE TITLE
连接的安全性如何保证

### ISSUE THREAD

**Issue by YIDWang** [zhiqiangxu/qrpc#4]
客户端的连接发起，如何进行鉴权。保证用户正确性

**Comment by zhiqiangxu** [comment]
鉴权也属于上层业务，http上鉴权的方法可以复用，唯一的区别是，鉴权通过后可以对连接做个标记，就不用重复鉴权了

**Comment by YIDWang** [comment]
哦哦 了解。我这边了解到 如果使用tls 或者 https场景，服务端每秒完成连接数是有瓶颈的，请问这种场景您遇到过吗？如何解决，单机百万连接的建联律的问题？（8w 的 QPS）

**Comment by zhiqiangxu** [comment]
解决性能问题，就是不断根据pprof做优化。另一种方案是使用tls proxy，比如stunnel之类的，把tls分担出去。

**Comment by YIDWang** [comment]
好的，了解。感谢回复。

**Comment by zhiqiangxu** [comment]
`qrpc`新增了`tls`支持，使用很简单，只要传入`tls.Config`即可，详参：https://github.com/zhiqiangxu/qrpc/blob/master/test/qrpc_tls_test.go
