### ISSUE TITLE
什么时候支持go-1.13

### ISSUE THREAD

**Issue by rubinliudongpo** [zhiqiangxu/qrpc#6]
目前在go-1.12-14之下
```golang
go get  -u   .

```
一直提示依赖性缺失.

**Comment by zhiqiangxu** [comment]
> 目前在go-1.12-14之下
> 
> ```go
> go get  -u   .
> ```
> 
> 一直提示依赖性缺失.

被强了吧？我目前项目是1.12

**Comment by zhiqiangxu** [comment]
> 目前在go-1.12-14之下
> 
> ```go
> go get  -u   .
> ```
> 
> 一直提示依赖性缺失.

`go get .`，不要`-u`试试？我这边用的是1.12

**Comment by rubinliudongpo** [comment]
vendor分支上, go-1.13, go-1.12都可以了
