### ISSUE TITLE
建议弄个完整的文章

### ISSUE THREAD

**Issue by JeffreyBool** [zhiqiangxu/qrpc#8]
协议设计
架构
api
更多的例子，
加入自定义鉴权方式

**Comment by zhiqiangxu** [comment]
可以看下readme里的那个ppt，整理比较清晰。例子都在test目录下面。

**Comment by JeffreyBool** [comment]
此外，qrpc还提供了桥接网络的特性，该特性使得多协议支持不费吹灰之力，同样的一套代码可以同时跑在tcp、websocket及任意已有的协议之下,
这个桥接网络是啥意思，没太懂， 如果自己需要再实现 tcp 连接怎么做呢

**Comment by zhiqiangxu** [comment]
桥接是指底层协议从tcp换成websocket之类的其他协议，可以看下ws目录下的readme

自己再实现tcp是说自定义包格式？

**Comment by JeffreyBool** [comment]
但是我看到代码 是 将 tcp 转换成了 ws

**Comment by zhiqiangxu** [comment]
> 但是我看到代码 是 将 tcp 转换成了 ws

没错呀，ws的作用就是把tcp替换成ws，比如浏览器端就会用到

**Comment by JeffreyBool** [comment]
能来个 tcp 客户端 协议拼装的例子就好了？看 qrpc 把客户端和服务端的协议都在框架内部封装了，对外不知道咋拼装协议。  还有能来个代码运行的架构就好了？

**Comment by JeffreyBool** [comment]
群主代码封装的挺好的，注释也挺好的。go 各种思想用的贼溜，回调函数接口等，能否告诉下怎么学这些吗，目前感觉自己代码封装不够好，完全想不到还有这种写法，每次看了都觉得耳目一新的感觉

**Comment by zhiqiangxu** [comment]
> 能来个 tcp 客户端 协议拼装的例子就好了？看 qrpc 把客户端和服务端的协议都在框架内部封装了，对外不知道咋拼装协议。 还有能来个代码运行的架构就好了？

真巧，刚写了个：

https://github.com/zhiqiangxu/qrpc/blob/master/tool/packet/main.go

```
$ go run main.go -c 0x10 -f 1 -r 100 -p abc
packet is: 0000000f000000000000006401000010616263
length:0000000f
requestID:0000000000000064
flag:01
cmd:000010
payload:616263
```

**Comment by zhiqiangxu** [comment]
> 群主代码封装的挺好的，注释也挺好的。go 各种思想用的贼溜，回调函数接口等，能否告诉下怎么学这些吗，目前感觉自己代码封装不够好，完全想不到还有这种写法，每次看了都觉得耳目一新的感觉

过奖了，多读多实践：）

**Comment by JeffreyBool** [comment]
据说改为 epoll 方式性能更高？

**Comment by zhiqiangxu** [comment]
go内部已经自动用epoll/kqueue管理了，自己管理epoll，性能不会提高，但是可以节省内存

**Comment by JeffreyBool** [comment]
tcp 粘包解决了吗

**Comment by zhiqiangxu** [comment]
> tcp 粘包解决了吗

线上跑了一年多了
