### ISSUE TITLE
关于cmd 的问题

### ISSUE THREAD

**Issue by JeffreyBool** [zhiqiangxu/qrpc#9]
现在基于 cmd == >业务,

如果要做认证，想到的是加个 auth 的 cmd, 但是客户端发送消息，可以不优先发送 auth 的 cmd 命令。

这样就绕过了登录， 是不是应该有个全局接收到消息的回调函数呢？ 或者客户端第一次连接的回调函数

**Comment by zhiqiangxu** [comment]
frame.ConnectionInfo().SetAnything可以记录状态，cmd开头检查对应的状态即可。

**Comment by JeffreyBool** [comment]
每个 cmd 都要检查一遍？

**Comment by JeffreyBool** [comment]
不能像close conn 客户端一样加个启动的回调吗

**Comment by zhiqiangxu** [comment]
> 每个 cmd 都要检查一遍？

可以加到middleware里面
